### ISSUE TITLE
[Feature Request] Will there be a TFLite version with quantization? Thank you

### ISSUE THREAD

**Issue by thelou1s** [RicherMans/CED#4]

**Comment by RicherMans** [comment]
Hey there,
so I actually deploy my models using TF-lite. However there are some problems with the current model and TF-lite, most notably its the GeLU activation that (depends on the version) is not supported by TFLite.
Thus you would need to retrain a model using Relu activation in order to make it work.
Kind regards,
Heinrich

**Comment by thelou1s** [comment]
@RicherMans Richer，Hi，does it have pytorch mobile version? thanks

**Comment by RicherMans** [comment]
Hey @thelou1s ,
as stated above you would need to retrain and then export to TFLite.
So from my side, no I won't retrain the model for that purpose only, but I think it shouldn't be a big deal, just initialize with ReLU activations from a checkpoint and then finetune.
Kind regards,
Heinrich
