### ISSUE TITLE
On the issue of model derivation

### ISSUE THREAD

**Issue by AntyRia** [RicherMans/CED#6]
Hello, thank you for your contributions, I have some questions when using your model, for example, there is an error when I want to export it to onnx, how should I export it to onnx model?

**Comment by thelou1s** [comment]
@AntyRia, I can not run and test this model successfully now, Could you post your test code to huggingface space if possible? Thanks

**Comment by RicherMans** [comment]
Hey guys,
the conversion usually fails due to STFT not being supported by Onnx.
Since the code base is the same, I recomment you guys to checkout [this issue](https://github.com/RicherMans/UIT_Mobile/issues/3).
In short: remove the self.front_end from the model and extract features outside in some different code, that should work out.
Kind regards,
Heinrich
